name: CI

on: [push]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.work
          cache: true
          go-version: ">=1.19.5"
      - name: Depedencies
        run: yarn install --immutable
      - uses: anchore/sbom-action@v0
        with:
          path: .
          output-file: ./bom.json
          artifact-name: bom.json
          format: cyclonedx-json
      - name: Transmit generated SBOM to Manifest
        uses: manifest-cyber/manifest-github-action@main
        id: transmit
        with:
          apiKey: ${{ secrets.MANIFEST_API_KEY }}
          bomFilePath: "./bom.json"
          sbom-version: ""
          sbom-name: testing-monorepo
          sbom-output: cyclonedx-json
 